=== aws/codepipeline-starter-templates/templates/metadata/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "category": {
      "type": "string",
      "enum": ["Deployment", "release", "Automation", "Continuous Integration"]
    },
    "description": {
      "type": "string"
    },
    "badge": {
      "type": "string",
      "enum": ["Coming Soon", "New", "Default", "Popular"]
    },
    "icon-name": {
      "type": "string"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "template-location": {
      "type": "string"
    },
    "ui-hints-location": {
      "type": "string"
    }
  },
  "required": ["id", "name", "description", "icon-name", "tags", "template-location", "ui-hints-location"]
}

=== aws/codepipeline-starter-templates/templates/metadata/ci-schedule-build-maven.json
{
  "id": "ciScheduleBuildMaven",
  "name": "Schedule a maven build pipeline",
  "description": "Build a maven project periodically",
  "category": "Automation",
  "badge": "New",
  "icon-name": "maven",
  "tags": ["maven", "codebuild", "schedule"],
  "template-location": "./cloudformation/ci-schedule-build-maven.yaml",
  "ui-hints-location": "./ui-hints/ci-schedule-build-maven.json"
}

=== aws/codepipeline-starter-templates/templates/metadata/ci-schedule-build-gradle.json
{
  "id": "ciScheduleBuildGradle",
  "name": "Schedule a gradle build pipeline",
  "description": "Build a gradle project periodically",
  "category": "Automation",
  "badge": "New",
  "icon-name": "gradle",
  "tags": ["gradle", "codebuild", "schedule"],
  "template-location": "./cloudformation/ci-schedule-build-gradle.yaml",
  "ui-hints-location": "./ui-hints/ci-schedule-build-gradle.json"
}

=== aws/codepipeline-starter-templates/templates/metadata/ci-build-gradle.json
{
  "id": "ciBuildGradle",
  "name": "CI Build Gradle",
  "description": "Build a gradle project",
  "category": "Continuous Integration",
  "badge": "New",
  "icon-name": "gradle",
  "tags": ["gradle", "codebuild"],
  "template-location": "./cloudformation/ci-build-gradle.yaml",
  "ui-hints-location": "./ui-hints/ci-build-gradle.json"
}

=== aws/codepipeline-starter-templates/templates/metadata/ci-build-nodejs.json
{
  "id": "ciBuildNodeJS",
  "name": "CI Build NodeJS",
  "description": "Build a node js project",
  "category": "Continuous Integration",
  "badge": "New",
  "icon-name": "nodejs",
  "tags": ["nodejs", "codebuild"],
  "template-location": "./cloudformation/ci-build-nodejs.yaml",
  "ui-hints-location": "./ui-hints/ci-build-nodejs.json"
}
