=== aws/codepipeline-starter-templates/templates/metadata/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "category": {
      "type": "string",
      "enum": ["Deployment", "release", "Automation", "Continuous Integration"]
    },
    "description": {
      "type": "string"
    },
    "badge": {
      "type": "string",
      "enum": ["Coming Soon", "New", "Default", "Popular"]
    },
    "icon-name": {
      "type": "string"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "template-location": {
      "type": "string"
    },
    "ui-hints-location": {
      "type": "string"
    }
  },
  "required": ["id", "name", "description", "icon-name", "tags", "template-location", "ui-hints-location"]
}

=== aws/codepipeline-starter-templates/templates/metadata/ci-build-python.json
{  
  "id": "ciBuildPython",
  "name": "CI Build Python",
  "description": "Build a python project",
  "category": "Continuous Integration",
  "badge": "New",
  "icon-name": "python",
  "tags": ["python", "codebuild"],
  "template-location": "./cloudformation/ci-build-python.yaml",
  "ui-hints-location": "./ui-hints/ci-build-python.json"
}

=== aws/codepipeline-starter-templates/templates/metadata/ci-schedule-build-nodejs.json
{  
  "id": "ciScheduleBuildNodeJS",
  "name": "Schedule a nodejs build pipeline",
  "description": "Build a nodejs project periodically",
  "category": "Automation",
  "badge": "New",
  "icon-name": "nodejs",
  "tags": ["nodejs", "codebuild", "schedule"],
  "template-location": "./cloudformation/ci-schedule-build-nodejs.yaml",
  "ui-hints-location": "./ui-hints/ci-schedule-build-nodejs.json"
}

=== aws/codepipeline-starter-templates/templates/metadata/deploy-to-cfn.json
{
  "id": "deployToCfn",
  "name": "Deploy to CloudFormation",
  "description": "Deploy your cloud formation template",
  "category": "Deployment",
  "badge": "Default",
  "icon-name": "cloudformation",
  "tags": ["cloudformation", "cf"],
  "template-location": "./cloudformation/deploy-to-cfn.yaml",
  "ui-hints-location": "./ui-hints/deploy-to-cfn.json"
}

=== aws/codepipeline-starter-templates/templates/metadata/ci-build-maven.json
{
  "id": "ciBuildMaven",
  "name": "CI Build Maven",
  "description": "Build a maven project",
  "category": "Continuous Integration",
  "badge": "New",
  "icon-name": "maven",
  "tags": ["maven", "codebuild"],
  "template-location": "./cloudformation/ci-build-maven.yaml",
  "ui-hints-location": "./ui-hints/ci-build-maven.json"
}

=== aws/codepipeline-starter-templates/templates/metadata/test-on-reflect.json
{
  "id": "testOnReflect",
  "name": "Run Reflect Test",
  "description": "Run tests on Reflect",
  "category": "Continuous Integration",
  "badge": "New",
  "icon-name": "reflect",
  "tags": ["ui-test", "reflect", "reflect"],
  "template-location": "./cloudformation/test-on-reflect.yaml",
  "ui-hints-location": "./ui-hints/test-on-reflect.json"
}

=== aws/codepipeline-starter-templates/templates/metadata/deploy-to-ecs-fargate.json
{
  "id": "deployToEcsFargate",
  "name": "Deploy to ECS Fargate",
  "description": "Deploy a ECR image to Amazon ECS Fargate cluster",
  "category": "Deployment",
  "badge": "New",
  "icon-name": "ecs",
  "tags": ["ecr", "ecs", "fargate"],
  "template-location": "./cloudformation/deploy-to-ecs-fargate.yaml",
  "ui-hints-location": "./ui-hints/deploy-to-ecs-fargate.json"
}

=== aws/codepipeline-starter-templates/templates/metadata/deploy-to-ecr.json
{
  "id": "deployToEcr",
  "name": "Push to ECR",
  "description": "Build and push a new container image to Amazon ECR",
  "category": "Deployment",
  "badge": "New",
  "icon-name": "ecr",
  "tags": ["ecr"],
  "template-location": "./cloudformation/deploy-to-ecr.yaml",
  "ui-hints-location": "./ui-hints/deploy-to-ecr.json"
}

=== aws/codepipeline-starter-templates/templates/metadata/ci-schedule-build-python.json
{
  "id": "ciScheduleBuildPython",
  "name": "Schedule a python build pipeline",
  "description": "Build a python project periodically",
  "category": "Automation",
  "badge": "New",
  "icon-name": "python",
  "tags": ["python", "codebuild", "schedule"],
  "template-location": "./cloudformation/ci-schedule-build-python.yaml",
  "ui-hints-location": "./ui-hints/ci-schedule-build-python.json"
}
