=== aws/codepipeline-starter-templates/templates/ui-hints/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "supported-source-filters": {
      "type": "object",
      "patternProperties": {
        "^(owner|provider)$": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false
    },
    "constraints": {
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "type": "object",
          "properties": {
            "Required": {
              "type": "boolean"
            },
            "Arn": {
              "type": "boolean"
            },
            "MinLength": {
              "type": "number"
            },
            "MaxLength": {
              "type": "number"
            },
            "Contains": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      }
    },
    "placeholders": {
      "type": "object"
    },
    "text-editor-styles": {
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "type": "object",
          "properties": {
            "mode": {
              "type": "string",
              "enum": ["yaml", "json"]
            },
            "minLines": {
              "type": "integer"
            },
            "maxLines": {
              "type": "integer"
            }
          },
          "required": ["mode", "minLines", "maxLines"],
          "additionalProperties": false
        }
      }
    }
  },
  "additionalProperties": false
}

=== aws/codepipeline-starter-templates/templates/ui-hints/deploy-to-cfn.json
{
  "supported-source-filters": {
    "owner": ["CodeStarConnection"]
  },
  "constraints": {
    "ConnectionArn": {
      "Required": true,
      "Arn": true
    },
    "FullRepositoryId": {
      "Required": true,
      "MinLength": 1,
      "MaxLength": 255,
      "Contains": "/"
    },
    "BranchName": {
      "Required": true,
      "MinLength": 1,
      "MaxLength": 255
    },
    "CodePipelineName": {
      "Required": true,
      "MinLength": 1,
      "MaxLength": 100
    },
    "StackName": {
      "Required": true,
      "MinLength": 1,
      "MaxLength": 255
    },
    "TemplatePath": {
      "Required": true,
      "MinLength": 1,
      "MaxLength": 255
    },
    "TemplateConfiguration": {
      "MinLength": 1,
      "MaxLength": 255
    },
    "ParameterOverrides": {
      "MinLength": 1,
      "MaxLength": 255
    },
    "OutputFileName": {
      "Required": true,
      "MinLength": 1,
      "MaxLength": 255
    },
    "CloudFormationResourcePermissions": {
      "Required": true,
      "MinLength": 1
    },
    "RetentionPolicy": {
      "Required": true,
      "MinLength": 1,
      "MaxLength": 255
    }
  },
  "placeholders": {
    "TemplatePath": "template.yaml",
    "CloudFormationResourcePermissions": "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    { \n      \"Sid\": \"PermissionsForCloudFormation\",\n      \"Effect\": \"Allow\",\n      \"Action\": \"*\",\n      \"Resource\": \"*\"\n    }\n  ]\n}\n"
  },
  "text-editor-styles": {
    "CloudFormationResourcePermissions": {
      "mode": "json",
      "minLines": 11,
      "maxLines": 22
    }
  }
}

=== aws/codepipeline-starter-templates/templates/ui-hints/test-on-reflect.json
{
  "supported-source-filters": {
    "owner": ["CodeStarConnection"]
  },
  "constraints": {
    "ConnectionArn": {
      "Required": true,
      "Arn": true
    },
    "FullRepositoryId": {
      "Required": true,
      "MinLength": 1,
      "MaxLength": 255,
      "Contains": "/"
    },
    "BranchName": {
      "Required": true,
      "MinLength": 1,
      "MaxLength": 255
    },
    "CodePipelineName": {
      "Required": true,
      "MinLength": 1,
      "MaxLength": 100
    },
    "ReflectAPIKeySecretArn": {
      "Required": true,
      "Arn": true
    },
    "ReflectAPIKeySecretJsonKeyName": {
      "Required": true,
      "MinLength": 1,
      "MaxLength": 100
    },
    "ReflectSuiteId": {
      "Required": true,
      "MinLength": 1,
      "MaxLength": 255
    },
    "ReflectWaitForTestResults": {
      "Required": true,
      "MinLength": 1,
      "MaxLength": 255
    },
    "CICodeBuildSpec": {
      "Required": true,
      "MinLength": 1
    },
    "RetentionPolicy": {
      "Required": true,
      "MinLength": 1,
      "MaxLength": 255
    },
    "ReflectParamOverride": {
      "MinLength": 1,
      "MaxLength": 1000
    },
    "ReflectParamVariables": {
      "MinLength": 1,
      "MaxLength": 1000
    },
    "ReflectParamGitHub": {
      "MinLength": 1,
      "MaxLength": 255
    }
  },
  "placeholders": {
    "ReflectParamOverride": "{\n  \"hostnames\": [{\n    \"original\": \"prod.myapp.com\",\n    \"replacement\": \"staging.myapp.com\"\n  }],\n  \"cookies\": [{\n    \"name\": \"my-favorite-cookie\",\n    \"value\": \"chocolate-chip\",\n    \"domain\": \"myapp.com\",\n    \"expires\": 123456789,\n    \"httpOnly\": false,\n    \"maxAge\": 123,\n    \"path\": \"/\",\n    \"secure\": true\n  }],\n  \"headers\": [{\n    \"name\": \"X-Custom-Header\",\n    \"value\": \"custom-value\",\n    \"persist\": false\n  }],\n  \"localStorage\": [{\n    \"key\": \"my-local-key\",\n    \"value\": \"local-value\"\n  }],\n  \"sessionStorage\": [{\n    \"key\": \"my-session-key\",\n    \"value\": \"session-value\"\n  }]\n}",
    "ReflectParamVariables": "{\n  \"username1\": \"user+${alpha(8)}@example.com\",\n  \"password\": \"acompletelyunguessablepassword\"\n}",
    "ReflectParamGitHub": "{\n  \"owner\": \"repository-owner\",\n  \"repo\": \"my-repository-name\",\n  \"sha\": \"0f4212320f2cb6734583ebef3a4928d78d4f3fde\"\n}"
  },
  "text-editor-styles": {
    "CICodeBuildSpec": {
      "mode": "yaml",
      "minLines": 1,
      "maxLines": 22
    },
    "ReflectParamOverride": {
      "mode": "json",
      "minLines": 29,
      "maxLines": 29
    },
    "ReflectParamVariables": {
      "mode": "json",
      "minLines": 4,
      "maxLines": 22
    },
    "ReflectParamGitHub": {
      "mode": "json",
      "minLines": 5,
      "maxLines": 22
    }
  }
}
